backend:
  name: git-gateway

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Sayfalar"
    folder: "/"
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "İçerik", name: "body", widget: "text"}
